apiVersion: v1
kind: Service
metadata:
  name: minirpc
  namespace: default
spec:
  type: NodePort
  selector:
    run: minirpc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000
