FROM ubuntu
RUN set -x; buildDeps='libssl-dev g++ cmake git' \
    && apt-get update \
    && apt-get install -y $buildDeps \
    && mkdir -p /usr/src/miniRPC \
    && git clone https://github.com/wolfplain/miniRPC.git /usr/src/miniRPC \
    && cd /usr/src/miniRPC \
    && sh +x build.sh
# choose to clean the image just for execute binary 
# optional apt-get purge -y --auto-remove $buildDeps
WORKDIR /usr/src/miniRPC